name:                hdominion
version:             0.1.0.0
github:              "blaisepascal/hdominion"
license:             BSD3
author:              "Buddha Buck"
maintainer:          "blaisepascal@gmail.com"
copyright:           "2018 Buddha Buck"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/blaisepascal/hdominion#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hdominion-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdominion

tests:
  hdominion-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdominion
